import { NextApiRequest, NextApiResponse } from 'next';
import { createClient as createSupabaseClient } from '@supabase/supabase-js';
import { uploadGameZip, saveGeneratedGame } from '@/lib/supabase';

/**
 * pages/api/upload-game.ts
 * 
 * API endpoint for uploading generated game to Supabase
 * 
 * This endpoint:
 * 1. Verifies user is authenticated
 * 2. Receives Lua script content
 * 3. Creates ZIP file with script and README
 * 4. Uploads ZIP to Supabase storage
 * 5. Saves game metadata to database
 * 6. Returns download URL
 * 
 * Authentication is required - verified via Supabase session
 */

interface UploadGameRequest {
  gameName: string;
  description: string;
  gameType: string;
  theme: string;
  luaScript: string;
}

interface UploadGameResponse {
  success: boolean;
  downloadUrl?: string;
  gameId?: string;
  error?: string;
}

async function handler(
  req: NextApiRequest,
  res: NextApiResponse<UploadGameResponse>
) {
  // Only accept POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, error: 'Method not allowed' });
  }

  try {
    // ============ VERIFY AUTHENTICATION ============
    const supabase = createSupabaseClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL || '',
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''
    );

    // Get the auth token from cookies
    const token = req.cookies['sb-access-token'];
    if (!token) {
      return res.status(401).json({ success: false, error: 'Unauthorized' });
    }

    // Set the auth header
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return res.status(401).json({ success: false, error: 'Not authenticated' });
    }

    // ============ VALIDATE REQUEST ============
    const { gameName, description, gameType, theme, luaScript } =
      req.body as UploadGameRequest;

    if (!gameName || !luaScript || !gameType || !theme) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields',
      });
    }

    // ============ CREATE ZIP FILE ============
    // Dynamically import jszip (for server-side use)
    const JSZip = (await import('jszip')).default;
    const zip = new JSZip();

    // Add main Lua script
    const scriptFileName = `${gameName.replace(/\s+/g, '_')}_main.lua`;
    zip.file(scriptFileName, luaScript);

    // Add README with setup instructions
    const readme = `# ${gameName}

**Game Type:** ${gameType}
**Theme:** ${theme}
**Description:** ${description}

## Quick Start

1. Create a new Place in Roblox Studio
2. In the Explorer, find "Workspace"
3. Right-click > Insert Object > Script
4. Copy the contents of \`${scriptFileName}\`
5. Paste into the new Script
6. Click "Run" to test

## What's Included

- \`${scriptFileName}\` - Main game script (paste this into Roblox Studio)
- \`README.md\` - This file

## Next Steps

1. **Test in Studio** - Make sure the game runs
2. **Customize** - Edit the script to add your own features
3. **Add Assets** - Add models, sounds, and other assets
4. **Publish** - Upload your game to Roblox

## Support

For help with Roblox development:
- [Roblox Developer Hub](https://create.roblox.com)
- [Lua Scripting Guide](https://create.roblox.com/docs/scripting/index)
- [Community Forums](https://devforum.roblox.com)

---

Generated by RoboxGen AI
Created: ${new Date().toISOString()}
`;
    zip.file('README.md', readme);

    // Generate ZIP blob
    const zipBlob = await zip.generateAsync({ type: 'arraybuffer' });

    // ============ UPLOAD TO SUPABASE STORAGE ============
    const fileName = `${gameName.replace(/\s+/g, '_')}_${Date.now()}.zip`;

    const downloadUrl = await uploadGameZip(user.id, fileName, Buffer.from(zipBlob));

    // ============ SAVE TO DATABASE ============
    const gameRecord = await saveGeneratedGame(user.id, {
      prompt: description,
      game_name: gameName,
      game_type: gameType,
      theme,
      download_url: downloadUrl,
      lua_script: luaScript,
    });

    console.log(`[Upload] Game saved: ${gameName} for user ${user.id}`);

    // ============ RETURN SUCCESS ============
    return res.status(200).json({
      success: true,
      downloadUrl,
      gameId: gameRecord.id,
    });
  } catch (error: any) {
    console.error('[Upload] Error:', error);

    return res.status(500).json({
      success: false,
      error: error.message || 'Failed to upload game',
    });
  }
}

export default handler;
