import React, { useState } from 'react';
import { GeneratedGame } from '@/lib/store';
import { formatDate, copyToClipboard } from '@/lib/utils';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

/**
 * Game Card Component - HACKER/TERMINAL THEME
 * Displays a single generated game with download and share options
 */
interface GameCardProps {
  game: GeneratedGame;
  onDelete?: () => void;
}

const GameCard: React.FC<GameCardProps> = ({ game, onDelete }) => {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const handleCopy = async () => {
    const success = await copyToClipboard(game.luaScript);
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = async () => {
    setDownloading(true);
    try {
      // Create a ZIP file with the game files
      const zip = new JSZip();

      // Add the main Lua script
      zip.file(`${game.name.replace(/\s+/g, '_')}_main.lua`, game.luaScript);

      // Add a README
      const readme = `# ${game.name}

**Game Type:** ${game.type}
**Theme:** ${game.theme}
**Generated:** ${formatDate(game.createdAt)}

## Instructions

1. Create a new Place in Roblox Studio
2. Open the Command Bar (View > Command Bar or F6)
3. Copy the contents of \`${game.name.replace(/\s+/g, '_')}_main.lua\`
4. In Server Scripts, create a new Script and paste the code
5. Save and run in Studio to test

## Features
${game.description}

Generated by RoboxGen AI
`;
      zip.file('README.md', readme);

      // Generate and download
      const blob = await zip.generateAsync({ type: 'blob' });
      saveAs(blob, `${game.name.replace(/\s+/g, '_')}.zip`);
    } catch (error) {
      console.error('Download failed:', error);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="terminal-box border-2 border-neon-green p-6 space-y-4 font-mono" style={{
      boxShadow: '0 0 15px rgba(0, 255, 0, 0.3), inset 0 0 15px rgba(0, 255, 0, 0.05)',
    }}>
      {/* Header */}
      <div>
        <div className="flex items-start justify-between mb-2">
          <div>
            <h3 className="text-base font-bold text-neon-green">{game.name}</h3>
            <p className="text-xs text-neon-green opacity-50 mt-1">$ generated: {formatDate(game.createdAt)}</p>
          </div>
          <span className="px-2 py-1 text-xs font-medium bg-terminal-bg border-2 border-neon-cyan text-neon-cyan" style={{
            boxShadow: '0 0 8px rgba(0, 255, 255, 0.4)',
          }}>
            [{game.type}]
          </span>
        </div>
      </div>

      {/* Description */}
      <p className="text-xs text-neon-green opacity-70 line-clamp-2">{game.description}</p>

      {/* Theme Badge */}
      <div>
        <span className="inline-block px-2 py-1 text-xs font-medium bg-terminal-bg text-neon-magenta border-2 border-neon-magenta" style={{
          boxShadow: '0 0 8px rgba(255, 0, 255, 0.4)',
        }}>
          [THEME: {game.theme}]
        </span>
      </div>

      {/* Stats */}
      <div className="flex gap-4 text-xs text-neon-green opacity-60 pt-2 border-t-2 border-neon-green">
        <span>$ views: {game.views || 0}</span>
        {game.shared && <span className="text-neon-cyan">[SHARED]</span>}
      </div>

      {/* Actions */}
      <div className="flex gap-2 pt-2">
        <button
          onClick={handleCopy}
          className="flex-1 py-2 border-2 border-neon-green text-neon-green text-xs font-bold uppercase transition-all hover:text-neon-cyan hover:border-neon-cyan bg-terminal-bg"
          style={{
            boxShadow: copied ? '0 0 10px rgba(0, 255, 0, 0.6)' : 'none',
          }}
        >
          {copied ? '[COPIED]' : '[COPY_CODE]'}
        </button>
        <button
          onClick={handleDownload}
          disabled={downloading}
          className="flex-1 py-2 border-2 border-neon-cyan text-neon-cyan text-xs font-bold uppercase transition-all hover:border-neon-green hover:text-neon-green bg-terminal-bg disabled:opacity-50"
          style={{
            boxShadow: downloading ? '0 0 10px rgba(0, 255, 255, 0.6)' : 'none',
          }}
        >
          {downloading ? '[DOWNLOADING...]' : '[DOWNLOAD_ZIP]'}
        </button>
      </div>

      {/* Share Button */}
      <button className="w-full py-2 border-2 border-neon-magenta text-neon-magenta text-xs font-bold uppercase transition-all hover:shadow-lg bg-terminal-bg" style={{
        boxShadow: '0 0 8px rgba(255, 0, 255, 0.4)',
      }}>
        [SHARE_TIKTOK]
      </button>
    </div>
  );
};

export default GameCard;
